In [2]:
import pandas as pd
import os

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
os.listdir("./")

['.git',
 '.ipynb_checkpoints',
 'BOWDescriptions.csv.csv',
 'GradientBoostedTrees Popularity.ipynb',
 'LogisticRegression Popularity.ipynb',
 'Models(Will).ipynb',
 'Prediction using textual data.ipynb',
 'PreliminaryWork.ipynb',
 'Preprocessing Steam game description.ipynb',
 'preprocess_project.csv',
 'Project Preprocessing (1).ipynb',
 'Project Preprocessing.ipynb',
 'project_preprocess.csv',
 'RandomForest Popularity.ipynb',
 'Regression Models.ipynb',
 'steam.csv',
 'steam_description_data.csv',
 'TFIDFDescriptions.csv']

## Binning Steam owners

In [4]:
steamDescriptions=pd.read_csv("steam_description_data.csv")
steam=pd.read_csv("steam.csv")
steamDescriptions.head()

,steam_appid,detailed_description,about_the_game,short_description
0,10,Play the world's number 1 online action game. ...,Play the world's number 1 online action game. ...,Play the world's number 1 online action game. ...
1,20,One of the most popular online action games of...,One of the most popular online action games of...,One of the most popular online action games of...
2,30,Enlist in an intense brand of Axis vs. Allied ...,Enlist in an intense brand of Axis vs. Allied ...,Enlist in an intense brand of Axis vs. Allied ...
3,40,Enjoy fast-paced multiplayer gaming with Death...,Enjoy fast-paced multiplayer gaming with Death...,Enjoy fast-paced multiplayer gaming with Death...
4,50,Return to the Black Mesa Research Facility as ...,Return to the Black Mesa Research Facility as ...,Return to the Black Mesa Research Facility as ...

In [4]:
steam.owners=steam.owners.astype("string")
owners=steam.owners.str.split("-")

result=[]
for i in range(len(owners)):
    low=int(owners[i][0])
    high=int(owners[i][1])
    result.append(high)

steam["Owners"]=result

steam.head()

,appid,name,release_date,english,developer,publisher,platforms,required_age,categories,genres,steamspy_tags,achievements,positive_ratings,negative_ratings,average_playtime,median_playtime,owners,price,Owners
0,10,Counter-Strike,2000-11-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,124534,3339,17612,317,10000000-20000000,7.19,20000000
1,20,Team Fortress Classic,1999-04-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,3318,633,277,62,5000000-10000000,3.99,10000000
2,30,Day of Defeat,2003-05-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Valve Anti-Cheat enabled,Action,FPS;World War II;Multiplayer,0,3416,398,187,34,5000000-10000000,3.99,10000000
3,40,Deathmatch Classic,2001-06-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,1273,267,258,184,5000000-10000000,3.99,10000000
4,50,Half-Life: Opposing Force,1999-11-01,1,Gearbox Software,Valve,windows;mac;linux,0,Single-player;Multi-player;Valve Anti-Cheat en...,Action,FPS;Action;Sci-fi,0,5250,288,624,415,5000000-10000000,3.99,10000000

In [5]:
steam.head()

,appid,name,release_date,english,developer,publisher,platforms,required_age,categories,genres,steamspy_tags,achievements,positive_ratings,negative_ratings,average_playtime,median_playtime,owners,price,Owners
0,10,Counter-Strike,2000-11-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,124534,3339,17612,317,10000000-20000000,7.19,20000000
1,20,Team Fortress Classic,1999-04-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,3318,633,277,62,5000000-10000000,3.99,10000000
2,30,Day of Defeat,2003-05-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Valve Anti-Cheat enabled,Action,FPS;World War II;Multiplayer,0,3416,398,187,34,5000000-10000000,3.99,10000000
3,40,Deathmatch Classic,2001-06-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,1273,267,258,184,5000000-10000000,3.99,10000000
4,50,Half-Life: Opposing Force,1999-11-01,1,Gearbox Software,Valve,windows;mac;linux,0,Single-player;Multi-player;Valve Anti-Cheat en...,Action,FPS;Action;Sci-fi,0,5250,288,624,415,5000000-10000000,3.99,10000000

In [6]:
steam["popularity"]=pd.cut(steam["Owners"],bins=[0,20000,100000, 200000000], labels=["Low popularity","Average", "Popular"])
steam["popularity"].value_counts()

Low popularity    18596
Average            4754
Popular            3725
Name: popularity, dtype: int64

In [7]:
steam.head()

,appid,name,release_date,english,developer,publisher,platforms,required_age,categories,genres,steamspy_tags,achievements,positive_ratings,negative_ratings,average_playtime,median_playtime,owners,price,Owners,popularity
0,10,Counter-Strike,2000-11-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,124534,3339,17612,317,10000000-20000000,7.19,20000000,Popular
1,20,Team Fortress Classic,1999-04-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,3318,633,277,62,5000000-10000000,3.99,10000000,Popular
2,30,Day of Defeat,2003-05-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Valve Anti-Cheat enabled,Action,FPS;World War II;Multiplayer,0,3416,398,187,34,5000000-10000000,3.99,10000000,Popular
3,40,Deathmatch Classic,2001-06-01,1,Valve,Valve,windows;mac;linux,0,Multi-player;Online Multi-Player;Local Multi-P...,Action,Action;FPS;Multiplayer,0,1273,267,258,184,5000000-10000000,3.99,10000000,Popular
4,50,Half-Life: Opposing Force,1999-11-01,1,Gearbox Software,Valve,windows;mac;linux,0,Single-player;Multi-player;Valve Anti-Cheat en...,Action,FPS;Action;Sci-fi,0,5250,288,624,415,5000000-10000000,3.99,10000000,Popular

In [8]:
steamDescriptions.columns

Index(['steam_appid', 'detailed_description', 'about_the_game',
       'short_description'],
      dtype='object')

## Convert text data using TFIDF

In [9]:
corpus=steamDescriptions["detailed_description"]

In [10]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     /home/zhengy6/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [11]:
stopwords_english = stopwords.words('english')
stopwords_english.append("you")
stopwords_english.append("your")
def cleanText(data):
    p = re.compile(r'<.*?>')
    res=p.sub('', data)
    res=re.sub(r'[0-9]',"", res)
    res=re.sub(r'https?:\/\/[a-zA-Z0-9@:%._\+~#=\/\/]+', '', res)
    res=re.sub(r'_*', "", res)
    tokens=nltk.word_tokenize(res)
    tokens=[token.lower() for token in tokens if not token.lower() in stopwords_english]
    return " ".join(tokens)

In [12]:
# need to clean up html.
corpus=steamDescriptions["detailed_description"].apply(cleanText)
corpus.T

0        play world 's number online action game . enga...
1        one popular online action games time , team fo...
2        enlist intense brand axis vs. allied teamplay ...
3        enjoy fast-paced multiplayer gaming deathmatch...
4        return black mesa research facility one milita...
                               ...
27329    first indie game steam . played lot puzzle gam...
27330    ever lonely one could save complete self-destr...
27331    super star blast space based game challenging ...
27332    pursue snow-white deer enchanted forest discov...
27333    portal opened dark magic pouring ! close gatew...
Name: detailed_description, Length: 27334, dtype: object

In [31]:

def convertTFIDF(corpus):
    vectorizer = TfidfVectorizer(stop_words='english', strip_accents="ascii", min_df=0.1, max_df=0.95)
    tv_matrix=vectorizer.fit_transform(corpus )
    description=pd.DataFrame(tv_matrix.toarray())
    vocab = vectorizer.get_feature_names_out()
    description.columns=vocab
    return description

In [116]:
description=convertTFIDF(corpus)
description

,action,adventure,available,based,battle,best,build,challenge,challenging,character,...,try,unique,unlock,use,using,various,want,way,weapons,world
0,0.225381,0.000000,0.000000,0.224651,0.000000,0.0,0.0,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.163636
1,0.204416,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.458153,...,0.0,0.346357,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.210029,0.000000
2,0.000000,0.000000,0.000000,0.369677,0.000000,0.0,0.0,0.000000,0.000000,0.000000,...,0.0,0.314201,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000
4,0.395474,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27329,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,...,0.0,0.000000,0.295402,0.110792,0.0,0.0,0.289203,0.109237,0.000000,0.183624
27330,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.349669,0.000000,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000
27331,0.000000,0.000000,0.000000,0.119219,0.126525,0.0,0.0,0.000000,0.286334,0.000000,...,0.0,0.101329,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000
27332,0.000000,0.146759,0.171991,0.000000,0.000000,0.0,0.0,0.000000,0.345835,0.000000,...,0.0,0.000000,0.168732,0.000000,0.0,0.0,0.165192,0.000000,0.000000,0.000000
27333,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.187754,0.000000,0.000000,...,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000

In [117]:

# bigram=convertTFIDF(corpus, n_gram=2)
# bigram.head()

##  Convert to number using bag of words

In [118]:
def convertBOW(corpus):
    cv = CountVectorizer(min_df=0.1, max_df=0.95, strip_accents="ascii")
    cv_matrix = cv.fit_transform(corpus)
    # convert matrix to dataframe
    vocab = cv.get_feature_names_out()
    df=pd.DataFrame(cv_matrix.toarray())
    # add vocabulary names
    df.columns=vocab
    return df


corpus

0        play world 's number online action game . enga...
1        one popular online action games time , team fo...
2        enlist intense brand axis vs. allied teamplay ...
3        enjoy fast-paced multiplayer gaming deathmatch...
4        return black mesa research facility one milita...
                               ...
27329    first indie game steam . played lot puzzle gam...
27330    ever lonely one could save complete self-destr...
27331    super star blast space based game challenging ...
27332    pursue snow-white deer enchanted forest discov...
27333    portal opened dark magic pouring ! close gatew...
Name: detailed_description, Length: 27334, dtype: object

In [119]:
res=convertBOW(corpus)

In [120]:
res

,action,adventure,also,around,available,back,based,battle,become,best,...,unique,unlock,use,using,various,want,way,weapons,well,world
0,1,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,1,0,0,0,0,0,0,0,0,0,...,2,0,0,0,0,0,0,1,0,0
2,0,0,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27329,0,0,1,0,0,0,0,0,0,0,...,0,2,1,0,0,2,1,0,0,2
27330,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27331,0,0,0,1,0,0,1,1,0,0,...,1,0,0,0,0,0,0,0,1,0
27332,0,1,0,0,1,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,0
27333,0,0,1,0,0,0,0,0,2,0,...,0,0,0,0,0,0,0,0,1,0

In [121]:
description.dtypes

action       float64
adventure    float64
available    float64
based        float64
battle       float64
              ...
various      float64
want         float64
way          float64
weapons      float64
world        float64
Length: 89, dtype: object

In [122]:
from sklearn.linear_model import LinearRegression

In [123]:
y=steam.popularity
y.value_counts()

Low popularity    18596
Average            4754
Popular            3725
Name: popularity, dtype: int64

In [124]:
y.shape

(27075,)

In [125]:
res.shape

(27334, 111)

In [126]:
steamDescriptions.shape

#description.to_csv("TFIDFDescriptions",index=False)

(27334, 4)

In [127]:

description["steam_appid"]=steamDescriptions["steam_appid"]
description

,action,adventure,available,based,battle,best,build,challenge,challenging,character,...,unique,unlock,use,using,various,want,way,weapons,world,steam_appid
0,0.225381,0.000000,0.000000,0.224651,0.000000,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.163636,10
1,0.204416,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.458153,...,0.346357,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.210029,0.000000,20
2,0.000000,0.000000,0.000000,0.369677,0.000000,0.0,0.0,0.000000,0.000000,0.000000,...,0.314201,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,30
3,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,40
4,0.395474,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27329,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,...,0.000000,0.295402,0.110792,0.0,0.0,0.289203,0.109237,0.000000,0.183624,1065230
27330,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.349669,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,1065570
27331,0.000000,0.000000,0.000000,0.119219,0.126525,0.0,0.0,0.000000,0.286334,0.000000,...,0.101329,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,1065650
27332,0.000000,0.146759,0.171991,0.000000,0.000000,0.0,0.0,0.000000,0.345835,0.000000,...,0.000000,0.168732,0.000000,0.0,0.0,0.165192,0.000000,0.000000,0.000000,1066700
27333,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.187754,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,1069460

In [145]:
# shape of the two dataset is inconsistent so need to merge them.
description["steam_appid"]=steamDescriptions["steam_appid"]
X=pd.merge(steam,description,left_on="appid", right_on="steam_appid")
X=X.iloc[:,20:-1]

X["popularity"]=steam["popularity"]

X=X.dropna()
X.to_csv("TFIDFDescriptions", index=False)
X=X.sample(frac=1, random_state=0)
y=X.popularity
X=X.drop("popularity", axis=1)
X.shape

(27075, 89)

In [146]:
y=pd.get_dummies(y)
y.shape

(27075, 3)

In [147]:
X.shape

(27075, 89)

## See if TFIDF or BOW is better

In [150]:
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split, GridSearchCV
K=np.arange(20)+1
knn = KNeighborsClassifier(n_neighbors=10)
knnCV=GridSearchCV(knn, param_grid={"n_neighbors":K},return_train_score=True, n_jobs=-1 )

In [151]:
knnCV.fit(X,y)

KNeighborsClassifier(n_neighbors=10)

In [153]:
knn.score(X,y)

0.621606648199446

In [162]:
knnCV.best_score_

AttributeError: 'GridSearchCV' object has no attribute 'best_score_'

In [163]:
res["steam_appid"]=steamDescriptions["steam_appid"]
X=pd.merge(steam,res,left_on="appid", right_on="steam_appid")
X=X.iloc[:,20:-1]
X=X.dropna()

X["popularity"]=steam["popularity"]

X=X.dropna()
X.to_csv("BOWDescriptions", index=False)
X=X.sample(frac=1, random_state=0)
y=X.popularity
X=X.drop("popularity", axis=1)
X

,action,adventure,also,around,available,back,based,battle,become,best,...,unique,unlock,use,using,various,want,way,weapons,well,world
151,0,2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
16974,1,0,0,0,0,0,3,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11436,0,0,0,0,0,0,0,0,0,0,...,0,0,2,0,0,0,0,0,0,0
16469,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
759,0,0,0,0,0,0,0,1,0,0,...,1,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13123,0,1,0,0,0,0,1,0,0,0,...,1,0,0,0,0,0,1,0,0,1
19648,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
9845,0,0,1,0,0,1,0,0,0,2,...,0,0,0,0,0,0,1,0,0,0
10799,0,0,0,0,0,2,0,1,0,0,...,0,0,0,0,0,1,0,2,0,1
2732,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0

In [167]:
knn = KNeighborsClassifier(n_neighbors=100)
knn.fit(X,y)

KNeighborsClassifier(n_neighbors=100)

In [168]:
knn.score(X,y)

0.691708217913204

## Fit a model with preprocessed features in steam.csv and the preprocessed textual feature

In [ ]:
steamP=pd.read_csv("project_preprocess.csv")

In [ ]:
steamP.head()

In [ ]:
steamP["positive_ratings"]=(steamP["positive_ratings"]-steamP["positive_ratings"].mean())/steamP["positive_ratings"].std()

In [ ]:
steamP=steamP.drop("positive_ratings", axis=1)

In [ ]:
y=steamP.popularity

In [ ]:
X=steamP.drop("popularity", axis=1)

In [ ]:
lr=LinearRegressor()